### ISSUE TITLE
u-law encoding

### ISSUE THREAD

**Issue by nakosung** [ibab/tensorflow-wavenet#109]
Paper indicates wavenet encodes waveform in u-law encoding. :)

https://github.com/ritheshkumar95/WaveNet/blob/master/dataset.py#L177

**Comment by lemonzi** [comment]
That is implemented in https://github.com/ibab/tensorflow-wavenet/blob/master/wavenet/ops.py#L44.

**Comment by nakosung** [comment]
Oh, I didn't know that. Closing issue.
