### ISSUE TITLE
Broken link to sample output in the readme

### ISSUE THREAD

**Issue by pender** [ibab/tensorflow-wavenet#135]
Loading the [SoundCloud-hosted audio sample linked in the readme](https://soundcloud.com/user-731806733/speaker-p280-from-vctk-corpus-1) gives the following error:

> We can’t find that track.
> Did you try to access a private track while not being signed in?
> Maybe the track has been removed.

**Comment by jyegerlehner** [comment]
Right, there's a PR pending to fix that:
https://github.com/ibab/tensorflow-wavenet/pull/132

**Comment by pender** [comment]
Whoops, sorry for the duplicate. Closing.
