### ISSUE TITLE
python train.py hangs on wrong path instead of raising error

### ISSUE THREAD

**Issue by urimerhav** [ibab/tensorflow-wavenet#150]
Hi all, awesome project! I checked it out and wasn't able to run the training procedure.

Running 
`python train.py ` causes the code to run properly up to this line:
`               summary, loss_value, _ = sess.run(
                    [summaries, loss, optim],`
At this point the code hangs forever.

I think this may be a symptom of the queue runners failing to fetch input data, I got the same error when I don't have a dataset file. However, I have downloaded the VCTK dataset and placed it in the correct folder. Any help in figuring out how to debug the data fetching part (or otherwise resolving this issue) would be greatly appreciated.

If it matters, I'm running tensorflow '0.11.0rc0'

**Comment by urimerhav** [comment]
Never mind. I did have a data path problem after all!

I think the queue runners should raise an error if they fail to load any audio files instead of running an infinite failed loop. I'll keep this issue closed in case someone else hits on the same error.

**Comment by jyegerlehner** [comment]
@urimerhav I wouldn't have closed this. train.py shouldn't hang when you give it a bad path. It should fail with an error message.

**Comment by nakosung** [comment]
I got same problems several times.

2016년 10월 15일 (토) 오전 9:28, jyegerlehner <notifications@github.com>님이 작성:
