### ISSUE TITLE
.wav was ignored as it contains only silence...

### ISSUE THREAD

**Issue by LucNaterop** [ibab/tensorflow-wavenet#159]
When running `train.py` on a single sound file I get

`Warning: corpus/file.wav was ignored as it contains only silence. Consider decreasing trim_silence threshold, or adjust volume of the audio.`

And no training happens. The volume is not low. The same thing works on another machine. 

Here's where it is being triggered:
https://github.com/ibab/tensorflow-wavenet/blob/master/wavenet/audio_reader.py#L98

I know that it cannot be a result of the (lacking) backend for audioread because `librosa.load('file.wav')` gives me the correct output (same as on other machine where it is working). 

Any ideas?

**Comment by lemonzi** [comment]
> I answered via mail and didn't get published, so weird... Reposting.

The unit of the `trim_silence` threshold is raw amplitude, which is kinda hard to tune. If you are experimenting with audios other than VCTK, I'd suggest setting it to 0 to prevent it from causing any trouble with `--silence_threshold=0`. 

Another possible source of bugs could be the shaping; some functions expect a num_samples x num_channels matrix, not a single vector.

**Comment by LucNaterop** [comment]
@lemonzi That seems to work, thanks!!

**Comment by lemonzi** [comment]
The unit of the `trim_silence` threshold is raw amplitude, which is kinda
hard to tune. If you are experimenting with audios other than VCTK, I'd
suggest setting it to 0 to prevent it from causing any trouble with
`--silence_threshold=0`.

Another possible source of bugs could be the shaping; some functions expect
a num_samples x num_channels matrix, not a single vector.

El dv., 21 oct. 2016 a les 16:47, Luca Naterop (<notifications@github.com>)
va escriure:
