### ISSUE TITLE
Generate specific words

### ISSUE THREAD

**Issue by noxerr** [ibab/tensorflow-wavenet#172]
Is there a way to generate sounds from a text? I mean, train it and then tell it to generate voice saying: hello world and so on? or it generates only random sentences?

**Comment by pineking** [comment]
See [issue 112](https://github.com/ibab/tensorflow-wavenet/issues/112).

**Comment by lemonzi** [comment]
Indeed. What you're looking for is local conditioning on language features, which is not implemented yet. Right now it generates random speech-like sounds (not random words).
