### ISSUE TITLE
New management

### ISSUE THREAD

**Issue by jyegerlehner** [ibab/tensorflow-wavenet#183]
Sorry guys but I don't have bandwidth to serve as the sole curator on this project, and give due consideration to everyone's issues and PRs, and fair consideration of PRs with changes that conflict with my own. I think that requires someone independently to mediate. So I've removed myself as a collaborator. Perhaps ibab can appoint someone willing to serve the role.

**Comment by ibab** [comment]
No worries, @jyegerlehner.
I've been extremely busy during the past few weeks and didn't have enough time to take care of the repo :(
Thanks for putting in so much work 👍

**Comment by akademi4eg** [comment]
So who is in charge of the repo at the moment?
Last update to master branch is 3 month ago and it seems like most of activity is only on the forum.
I'm currently studying code from this repo and training models using other forks (like the one from global conditioning PR by @jyegerlehner). If there are no volunteers among current contributors, I can spare some time for repo management.

**Comment by lemonzi** [comment]
@ibab and myself are the current maintainers, although it seems we are both too busy (I'm dealing with my thesis and several freelancing gigs ATM). New volunteers would be greatly appreciated. @ibab is the owner so it's up to him, but in the past we requested that maintainers perform a couple of code reviews before giving them write access, to ensure a consistent quality standard.

**Comment by ibab** [comment]
Hi @akademi4eg!
I've been super busy the past few months and didn't have time to maintain
the project.
I'll add maintainers later today once I'm back at my computer.
It would be nice to keep the code quality standard high, but keeping the
project going is more important IMO.
I'd also like to get the repo out of my namespace and into an organization
to encourage more people to contribute.
