### ISSUE TITLE
Using the quantization technique to speed up generating wav

### ISSUE THREAD

**Issue by MingAnLin** [ibab/tensorflow-wavenet#187]
Hi,guys! Can we using the quantization technique( https://petewarden.com/2016/05/03/how-to-quantize-neural-networks-with-tensorflow/ ) to   speed up generating wav?

**Comment by lemonzi** [comment]
We could, yes. This is not production code, though, so the goal is not to optimize it as much as possible.

That being said, there are other factors that have more impact on the runtime, such as the fact that each sample requires a call to `session.run()`. It would be much faster to create a dynamic graph using something like `tf.while()`, `tf.scan()`, or TensorFlow Fold.
