### ISSUE TITLE
Error when using wav_seed file to start generating

### ISSUE THREAD

**Issue by Nimeas** [ibab/tensorflow-wavenet#188]
Hi, 

I just want to point to a problem with `create_seed` method which occurs when generating is conditioned by wav seed file.

>  Traceback (most recent call last):
>   File "generate.py", line 247, in <module>
>     main()
>   File "generate.py", line 159, in main
>     quantization_channels)
>   File "generate.py", line 110, in create_seed
>     return quantized[:cut_index]
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 313, in _SliceHelper
>     if s.stop is not None and s.stop < 0:
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 529, in __nonzero__
>     raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
> TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use the logical TensorFlow ops to test the value of a tensor.

I'd suggest using numpy operations instead of tensorflow methods which return tensors for `cut_index` calculation.

**Comment by fehiepsi** [comment]
Could you provide more details to reproduce your error? There is no error in my case. I used tensorflow 0.11rc2 and 0.11.

**Comment by ghoshaw** [comment]
I have the same problem. 
The code I use is as follows:
python generate.py --wav_out_path=generated.wav --samples 16000 --wav_seed ../twinkle_twinkle.wav ./logdir/train/2016-11-29T16-41-14/model.ckpt-1600

and the error is 
Traceback (most recent call last):
  File "generate.py", line 251, in <module>
    main()
  File "generate.py", line 163, in main
    quantization_channels)
  File "generate.py", line 113, in create_seed
    return quantized[:cut_index]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 313, in _SliceHelper
    if s.stop is not None and s.stop < 0:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 529, in __nonzero__
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use the logical TensorFlow ops to test the value of a tensor.

**Comment by Nimeas** [comment]
> Could you provide more details to reproduce your error? There is no error in my case. I used tensorflow 0.11rc2 and 0.11.

@fehiepsi of course:

- Ubuntu Desktop 16.04.1 (64-bit)
- Python 2.7.12
- Tensorflow 0.10.0rc0 with GPU enabled

> $ python generate.py --samples 48000 --logdir logdir/generate --window 32000 --wavenet_params wavenet_params.json --wav_out_path output.wav --save_every 4000 --wav_seed 2sec.wav logdir/labrosa_syn/model.ckpt-2750
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
> I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
> name: GeForce GTX 950M
> major: 5 minor: 0 memoryClockRate (GHz) 0.928
> pciBusID 0000:01:00.0
> Total memory: 4.00GiB
> Free memory: 3.39GiB
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:839] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0)
> Restoring model from logdir/labrosa_syn/model.ckpt-2750
> Traceback (most recent call last):
>   File "generate.py", line 251, in <module>
>     main()
>   File "generate.py", line 163, in main
>     quantization_channels)
>   File "generate.py", line 114, in create_seed
>     return quantized[:cut_index]
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 313, in _SliceHelper
>     if s.stop is not None and s.stop < 0:
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 529, in __nonzero__
>     raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
> TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use the logical TensorFlow ops to test the value of a tensor.


Although I solved this ad-hoc by replacing tensor ops with numpy methods, I'll retry with latest TF version and post here if that solves the issue.

**Comment by Nimeas** [comment]
Update of TF to version `0.12.1-cp27` solved the issue.
