### ISSUE TITLE
Recommended parameters to compare to fast-wavenet example?

### ISSUE THREAD

**Issue by tszumowski** [ibab/tensorflow-wavenet#194]
I'd like to compare training/generation times to the [fast-wavenet](https://github.com/tomlepaine/fast-wavenet) implementation. I understand the **generation** component from that implementation was merged in a while, but I'd like to try out the same parameters between the two. 

I'm training using the sample 44.1kHz clip in under [assets/voice.wav](https://github.com/tomlepaine/fast-wavenet/tree/master/assets) from the fast-wavenet. So I modified "sample_rate" in wavenet_params.json to 44100 (from 16000). 

Where I get a bit lost is in the dilation and channels parameters. fast-wavenet has:
```
num_channels=1,
num_classes=256,
num_blocks=2,
num_layers=14,
num_hidden=128
```

Using this configuration for fast-wavenet, my machine (DIGITS box) trains to <0.1 cost in about 5 minutes. 

What would be the equivalent (or close to equivalent) parameters for this implementation under _wavenet_params.json_?

**Comment by jyegerlehner** [comment]
I'll just point out one that you would surely stumble over with 44.1KHz audio: the --window size command line arg would need to be specified, and should be set to the receptive field size of your net. It defaults to 8000, and at 44.1KHz that's only 181 mSec, which is probably too short. Or better yet, you could use [koz4k's PR](https://github.com/ibab/tensorflow-wavenet/pull/191) which eliminates the --window parameter in favor of using the receptive field size. 

I'm not familiar with fast-wavenet so at the moment can't help with mapping their parameters to tensorflow-wavenet's.

**Comment by tszumowski** [comment]
@jyegerlehner Thanks for the tip. I didn't realize that --window field. I was concerned that there may be some mismatch between sample sizes so I re-encoded that 44.1kHz voice.wav to a 16kHz file to maintain compatability. It's still just generating static for me using the default parameters after ~1000 steps (loss=0.01). So I'm still actively debugging to see if it's some encoding issue or something.

**Comment by tszumowski** [comment]
UPDATE:
Still no luck getting a decent reproduction of the wave file from fast-wavenet's "voice.wav" file. But since they're different architectures, it's not really fair for me to ask for parity. So I'll close this issue.
