### ISSUE TITLE
Is Streaming The Audio File a Possibility?

### ISSUE THREAD

**Issue by mrsylerpowes** [ibab/tensorflow-wavenet#197]
Is it possible to stream the training audio file if it is a non-local file (HTTP or FTP Uri) using the Python io library or some other streaming library for training? I didn't take a real look at the code to see whether this is possible with the AudioReader library that is currently being used. If this cannot be implemented that way could there be a way to download the file by inputting the non-local Uri? I believe this would be more convenient than the current way of training.

**Comment by vonpost** [comment]
As WaveNet is as far from realtime performance as the word permits I don't really see why this would be useful (other than a wget less). Can you elaborate on why this would be convenient?

**Comment by mrsylerpowes** [comment]
@vonpost The current file that is being used is 10 Gigabytes and to be able to stream the  parts of the file that are needed for training would be convenient?
