### ISSUE TITLE
Rewrite the input pipeline using a proper Python audio library

### ISSUE THREAD

**Issue by ibab** [ibab/tensorflow-wavenet#2]
Unfortunately, there's currently no easy way to disable the verbose logging output from ffmpeg that results from loading the `.wav` files into TensorFlow.
(I've recompiled TensorFlow to disable the output while developing the network).

I can use a different library to decode the `.wav` files, but that would add an extra dependency (and some extra code).

**Comment by genekogan** [comment]
[audiolab](http://cournape.github.io/audiolab/intro.html) is i think probably the most minimal library, or you could consider [librosa](https://github.com/librosa/librosa/) which is really nice but probably has more features than you need.

**Comment by ibab** [comment]
Thanks!
I actually started out with librosa, but switched when I realized that tensorflow has built in methods for loading audio files.
It can be used by loading the waveform as a numpy array and manually enqueueing it using a placeholder.

**Comment by ibab** [comment]
If someone is interested in adding a custom input pipeline that uses `audiolab` or `librosa`, that would be a really nice contribution.
This would allow us to do more advanced preprocessing in the future like compressing the input waveform, etc.

It shouldn't be too difficult to add this.
We just need to start an extra thread that repeatedly runs `sess.run(enqueue, feed_dict={X: input})` where `enqueue` is an op that places the placeholder `X` into the queue, and `input` is the numpy array that we get out of our custom preprocessing.

**Comment by genekogan** [comment]
librosa has a lot of really nice features that could be useful for pre-processing, like detecting onsets/beats/musical events. it could be helpful to do more advanced segmentation of the input audio, or creating labels. but i don't know if this might be out of scope for this repo. i'll have to investigate how to use the session thread right, but just getting samples from librosa is a piece of cake.

**Comment by ibab** [comment]
@genekogan: Cool, you can leave a message here if there's a problem with getting the separate thread (or group of threads) to work.

**Comment by lemonzi** [comment]
Another option is to use tf.slim, which is included with tensorflow and has
wrappers for this kind of tasks.

**Comment by genekogan** [comment]
i don't fully understand how to set up sessions/threads, but think i'm on the right track, so posting what i have.

this scans a directory recursively for audio file paths.

```
import fnmatch

def scan_directory(directory, ext="wav"):
    files = []
    for root, dirnames, filenames in os.walk(directory):
        for filename in fnmatch.filter(filenames, '*.%s'%ext):
            files.append(os.path.join(root, filename))
    return files
```

iterating through them, loading them with librosa, and adding to the queue (0 speaker label for the moment).

```
import librosa

files = scan_directory(args.data_dir)

for f in files:
        audio, sr = librosa.load(f, sr=wavenet_params["sample_rate"], mono=True)
        speaker = 0  # make this 0 for now
        sess.run(enqueue, feed_dict={X: audio})
```

should this `sess` be separate from the main one?  and i gather `enqueue` should be instantiated before as  `enqueue = queue.enqueue([audio, speaker])` where audio and speaker should just be placeholders, instead of what came from the ffmpeg loader?

**Comment by ibab** [comment]
This looks good.
Some comments:
 - In the current implementation I've used `glob` to collect the files, but using `os.walk` is also fine. Here's where the list of filenames currently gets created: https://github.com/ibab/tensorflow-wavenet/blob/badfbd2f381729b1ee4d2f99a936cbacfa4f4a15/train.py#L57
 - You're right that the `enqueue` op needs to be created as you've described
 - Your code will block as soon as the queue is completely full. The idea is to use the `threading` module to run a background thread that keeps running `sess.run(enqueue, ...)`. That way the queue will get refilled in the background.

**Comment by genekogan** [comment]
i used `os.walk` so it can work recursively on any directory structure. i think `glob` can only do recursive in python 3+ or (as in the case of VCTK) we just know the subdirectories ahead of time.

would something like [this](https://indico.io/blog/tensorflow-data-input-part2-extensions/) be the right approach? i.e. make a threaded queue runner and use `tf.train.start_queue_runners` after setting up the network.

**Comment by ibab** [comment]
Right, that makes the os.walk approach superior. Ideally we'd want to be
able to train on any collection of wav files and not assume the VCTK
directory structure.

That example is excellent for what we want to do. Note that the example
sets up a custom thread, which won't be started when using
tf.train.start_queue_runners.

**Comment by genekogan** [comment]
it would start when we start the custom runner, i believe:

```
tf.train.start_queue_runners(sess=sess)
custom_runner.start_threads(sess)
```

**Comment by genekogan** [comment]
ok i think i'm on the right track. i made a `CustomRunner` class which iterates through the data with librosa. but i'm still having some problems -- i think i setup the placeholder wrong (how can i get it to accommodate variable-length audio?)

the code is [in my fork here](https://github.com/genekogan/tensorflow-wavenet/blob/master/train2.py). i made a temp file `train2.py` to keep a copy of the working one.

when i run it, i get:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "train2.py", line 91, in thread_main
    sess.run(self.enqueue, feed_dict={self.dataX:audio})
  File "/mnt/drive1/virtualenvs/caffe/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/mnt/drive1/virtualenvs/caffe/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 640, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (55990,) for Tensor u'create_inputs/Placeholder:0', which has shape '(?, 1)'
```

**Comment by lemonzi** [comment]
From the error, you're feeding a 1D array and it expects something 2D but with the second dimension set to 1; you'll have to reshape or expand_dims one of them.

**Comment by lemonzi** [comment]
https://github.com/genekogan/tensorflow-wavenet/blob/master/train2.py#L77 Remove the `, 1` from here?

**Comment by genekogan** [comment]
thank you, that (and a couple other changes) fixes it. X needs to be reshaped to 2d which i just added to the loading.

see [updated](https://github.com/genekogan/tensorflow-wavenet/blob/master/train2.py).

i am now getting normal output, but i haven't verified if it works as the ffmpeg version does. i'll check tomorrow, and i can also update `generate.py` to use librosa for post/saving, and send a PR if it all looks correct.

```
$ python train2.py --data_dir ../../data/VCTK-Corpus/
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.19
pciBusID 0000:01:00.0
Total memory: 12.00GiB
Free memory: 11.10GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:839] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0)
step 0 - loss = 6.977, (3.121 sec/step)
Storing checkpoint to ./logdir/train/2016-09-18T00:48:59.740392/model.ckpt
step 1 - loss = 5.518, (1.974 sec/step)
step 2 - loss = 5.585, (2.329 sec/step)
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:244] PoolAllocator: After 4912 get requests, put_count=4702 evicted_count=1000 eviction_rate=0.212675 and unsatisfied allocation rate=0.266694
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:256] Raising pool_size_limit_ from 100 to 110
step 3 - loss = 5.273, (2.190 sec/step)
step 4 - loss = 5.223, (2.151 sec/step)
step 5 - loss = 4.865, (2.115 sec/step)
step 6 - loss = 5.179, (1.984 sec/step)
step 7 - loss = 4.986, (1.859 sec/step)
step 8 - loss = 5.110, (2.021 sec/step)
step 9 - loss = 4.632, (2.080 sec/step)
...
```

**Comment by genekogan** [comment]
this is done as of [https://github.com/ibab/tensorflow-wavenet/commit/c79add15433c65ab7d44c3ba052a378b95fbc0f2](https://github.com/ibab/tensorflow-wavenet/commit/c79add15433c65ab7d44c3ba052a378b95fbc0f2).
