### ISSUE TITLE
How to prepare .wav files for training

### ISSUE THREAD

**Issue by Mega4alik** [ibab/tensorflow-wavenet#200]
Hello, I have collection of .wav files with following characteristics: 
Size - 54,628,204 bytes (54.6 MB on disk)
Sample rate - 44,100
Bits per sample - 16
Duration - 05:10
Audio channels - 2

What are optimal values for wavenet_params.json file?
Are there any additional actions I should take on preparing the data?

**Comment by akademi4eg** [comment]
Just run train.py script as stated in home page of this repo. It should do resampling and other necessary things internally.
