### ISSUE TITLE
Where could we get Mandarin Chinese corpus which is used by this project?

### ISSUE THREAD

**Issue by KevinYuk** [ibab/tensorflow-wavenet#208]
We can only find VCTK corpus (around 10.4GB) for English.

**Comment by KevinYuk** [comment]
We can only find VCTK corpus (around 10.4GB) for English.

**Comment by akademi4eg** [comment]
In the original paper they used single-speaker Chinese corpus for TTS. Probably that corpus is not publicly available.

Also as far as I know this project is an attempt by community to reproduce WaveNet. Thus we have access only to public domain corpuses like VCTK.
