### ISSUE TITLE
bug in _embed_gc

### ISSUE THREAD

**Issue by seehuhn** [ibab/tensorflow-wavenet#211]
The `_embed_gc()` method of class WaveNetModel contains the following lines:

    gc_batch_rank = len(global_condition.get_shape)
    dims_match = (global_condition.get_shape()[gc_batch_rank - 1] ==
                  self.global_condition_channels)

I believe that this is a typo.  Shouldn't it be `... = len(global_condition.get_shape())` (with extra brackets) instead?  I found this by reading the code, not sure whether this leads to actual problems.

**Comment by jyegerlehner** [comment]
Thanks seehuhn. 

Yes it would fail if anyone tried to use that feature. It's not used at the moment by the rest of the project. The WaveNetModel provides for two ways of globally conditioning: 1) where the global condition is indicated by an integer selecting from one of a number of mutually-exclusive ids (e.g. speaker id). This is the one the project is using. 2) where the global condition is provided to WaveNetModel as a vector of activations from some external source. That's the one with the bug you found. It's not hooked up to anything at the moment.

We should either fix or remove it.
