### ISSUE TITLE
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model

### ISSUE THREAD

**Issue by ianni67** [ibab/tensorflow-wavenet#217]
Sorry for posting newbye questions, but I really could not find a suitable solution on the web.
I consistently get the error message below when running generate.py after learning with my own data.
I run generate as follows:
`python generate.py --wav_out_path=generated.wav --save_every 2000 --samples 160000 model.ckpt-99999`
and get the following error message:
`W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model.ckpt-99999`
I'm running the last version of tensorflow.
Please help, I'm really puzzled.

**Comment by akademi4eg** [comment]
Try changing model.ckpt-99999 to path to your checkpoint file. It probably is something like logdir/model.ckpt-99999 or logdir/some-timestamp-here/model.ckpt-99999

**Comment by ianni67** [comment]
***SOLVED***
My bad. I felt it was some stupid detail, yet, did not catch it. Indeed I tried to feed the whole path, must have made some stupid typo. Thank you.

**Comment by AaronLeong** [comment]
I encountered the same problem, you solve it?

**Comment by ianni67** [comment]
@AaronLeong , 
akademi4eg provided the correct solution above. The problem is that we have to provide the whole path to the model. The file shall not have any extension and the path must be complete starting from the logdir, as stated above.
