### ISSUE TITLE
Channel size

### ISSUE THREAD

**Issue by multivac61** [ibab/tensorflow-wavenet#22]
[Here](https://github.com/ibab/tensorflow-wavenet/blob/master/wavenet.py#L11) you say that you will quantize the channels to 256 possible amplitude values (as is mentioned on page 3 in the original paper). When you run the quantization in the [preprocessing step](https://github.com/ibab/tensorflow-wavenet/blob/master/wavenet.py#L102) you cast the data from the mu-law companding transformation to a tf.int32 which can take on 4294967296 different values. Am I mistaken or should this be cast to a tf.int8 instead?

**Comment by multivac61** [comment]
Also, I am very happy to help with your contribution. Let me know if there is anything in particular that needs work.

**Comment by lemonzi** [comment]
It's arguably a waste of space, but the code is valid -- the quantization
is done by having a float that goes from 0 to 256 and then rounding it down
to the nearest integer. So, a bunch of bits will always be 0. The plus side
is that if we want to test it with more bits (say, 1024 values) the
datatype remains the same.
El dv., 16 set. 2016 a les 16:29, multivac61 (<notifications@github.com>)
va escriure:

**Comment by ibab** [comment]
Yeah, although the datatype is `int32`, only integers up to `mu` are actually produced.
