### ISSUE TITLE
code understanding of Queue data reader

### ISSUE THREAD

**Issue by weixsong** [ibab/tensorflow-wavenet#225]
Hi, 

In audio_reader.py,  this project use tf.PaddingFIFOQueue to provide data for the network.

My understanding of the input of network is 1 * 100000 * 1, 100000 samples each step. In the following code,  it will enqueue until the len(buffer_) is 0, then will this lead to the network input is not actually 100000 samples?

```python
                # Cut samples into fixed size pieces
                buffer_ = np.append(buffer_, audio)
                while len(buffer_) > 0:
                    piece = np.reshape(buffer_[:self.sample_size], [-1, 1])
                    sess.run(self.enqueue,
                             feed_dict={self.sample_placeholder: piece})
                    buffer_ = buffer_[self.sample_size:]
```

if len(buffer_) is 7000, then this 7000 samples will also be enqueued, then the network input is 1 * 7000 * 1,
is my understanding correct?

**Comment by Nimeas** [comment]
Hi @weixsong,

I think that your understanding of referenced code snippet is not correct, but it is not very relevant as well (old code version), so please check out the latest version of this repo. 

However, regarding your question, the following code
```python
piece = np.reshape(buffer_[:self.sample_size], [-1, 1])
sess.run(self.enqueue,
         feed_dict={self.sample_placeholder: piece})
```
tells, that `piece` will be of shape `(self.sample_size, 1)`. If by 

> network input

 you mean single observation fed to the network as an input, then this should answer your question. However, you may find that shape of the input tensor is further manipulated after dequeue operation, based on some experiment parameters. 

Additionally, you might also want to check out [Reading Data](https://www.tensorflow.org/programmers_guide/reading_data) and [Threading & Queues](https://www.tensorflow.org/programmers_guide/threading_and_queues) which I found useful when analyzing `audio_reader.py`.

Please, make sure that you are referencing latest version of the project code in your future issues.

Thanks

**Comment by weixsong** [comment]
Hi @Nimeas ,
thanks for your remind of latest code.

I debug with the latest code, and get the dequeued audio_batch, audio_batch is sent into network for training.

the actual shape differ each time because the reader and the wave lengths, here are some shapes:
(1, 50173, 1)
(1, 52221, 1)
(1, 22877, 1)
(1, 98301, 1)
...


It make sense for the convolution network to handle different length audio samples, this this feature added in order to corporate with global condition? Because if the audio samples are concatenated together for different people, then the global condition will be mixed for 2 people.

**Comment by Nimeas** [comment]
@weixsong regarding those shapes: there is parameter to `train.py` called `sample_size` which is set to `100000` by default and defines behavior of `AudioReader` by this pretty self-explanatory code: 

```python
# Cut samples into pieces of size receptive_field +
# sample_size with receptive_field overlap
while len(audio) > self.receptive_field:
    piece = audio[:(self.receptive_field +
                    self.sample_size), :]
    sess.run(self.enqueue,
             feed_dict={self.sample_placeholder: piece})
    audio = audio[self.sample_size:, :]
```

That should make clear why individual examples have different lengths. This means  no issue since [PaddingFIFOQueue](https://www.tensorflow.org/api_docs/python/tf/PaddingFIFOQueue#__init__) was used here.

Regarding your question:

> It make sense for the convolution network to handle different length audio samples, this this feature added in order to corporate with global condition? Because if the audio samples are concatenated together for different people, then the global condition will be mixed for 2 people.

I have no knowledge about causality of any design decision made in this project, but my opinion is, that concatenating audio snippets from multiple training files just doesn't make sense in any scenario, whether you train on speech, music or jungle sounds. But I agree with you, that global conditioning prohibits this approach, since each training example needs to be augmented with single speaker-id vector.

**Comment by weixsong** [comment]
@Nimeas , thanks very much for your comments.
