### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by ibab** [ibab/tensorflow-wavenet#24]
I'd like to add unit tests before extending the implementation further.
That should prevent us from pushing non-working versions of the code in the future.
TensorFlow has a nice API for tests, which I'd like to use for this: https://www.tensorflow.org/versions/r0.10/api_docs/python/test.html#testing

**Comment by multivac61** [comment]
I have started implementing unit tests - https://github.com/multivac61/tensorflow-wavenet/blob/unittests/test.py

@lemonzi has suggested that code that is independent on hyperparameters (_preprocessing etc) be moved outside the WaveNet class. That makes testing on them easier and it leads to better code structure.

**Comment by lemonzi** [comment]
Yep! I think we could move out `_preprocess` (which is actually `encode`), `decode`, `dilated_conv`, and maybe something more.

**Comment by ibab** [comment]
Yeah, we can create a `wavenet_ops.py` or just `ops.py` file that we can move all independent functions to.

**Comment by ibab** [comment]
I've added a first unit test at [`test/test_causal_conv.py`](https://github.com/ibab/tensorflow-wavenet/blob/0a60d90e5162de222601214e2e9998ba4b6f515f/test/test_causal_conv.py).

**Comment by lemonzi** [comment]
It seems we have decent unit tests for now. Pieces not covered yet should be listed in Projects or in the Wiki.
