### ISSUE TITLE
Is there a usage guide on how to generate specific-speech based on specific text/string?

### ISSUE THREAD

**Issue by NovaLeft** [ibab/tensorflow-wavenet#252]
Very cool project! 

So I looked at the readme and I can see how to generate sound by (for example) training on the voice corpus (VCTK i beleive), but once trained, how does one 'feed-in' or choose specific strings for which to generate the vocalization (of that string)?

Thanks!

**Comment by AlexClarke1** [comment]
I was wondering this too. Might be worth looking at Merlin as that uses the syntactical processing of Festival to generate actual text to speech.

**Comment by lemonzi** [comment]
You need a front-end that extracts linguistic features from the text, and then use local conditioning on the network (which is not fully implemented yet) to enforce them. See #226, #112, #235.
