### ISSUE TITLE
Running "pip install -r requirements.txt" breaks GPU-support

### ISSUE THREAD

**Issue by dage** [ibab/tensorflow-wavenet#274]
I've found that running
_pip install -r requirements.txt_
breaks GPU support on my Windows 10 Anaconda tensorflow-gpu environment.

Replacing 
_tensorflow>=1.0.0_
with
_tensorflow-gpu>=1.0.0_
seems to fix the issue.

Maybe create a requirements-gpu.txt in addition to requirements.txt and update the README?

**Comment by lemonzi** [comment]
Oh no... I was hoping pip would be clever enough to count tensorflow-gpu as satistfied package for tensorflow. I don't have a GPU myself, so I couldn't test it. Yes, what you suggest is the best solution, I'll push a fix right away. Thanks!
