### ISSUE TITLE
 Global conditioning is enabled, but file names do not conform to pattern having id.

### ISSUE THREAD

**Issue by HandsomeDevilv112** [ibab/tensorflow-wavenet#278]
`al@al-teletran1:~/tensorflow-wavenet$ python train.py --data_dir=corpus --num_steps 150000 --silence_threshold=0 --learning_rate .0001 --gc_channels 32`

> Using default logdir: ./logdir/train/2017-06-17T00-01-25
Traceback (most recent call last):
  File "train.py", line 337, in <module>
    main()
  File "train.py", line 228, in main
    silence_threshold=silence_threshold)
  File "/home/al/tensorflow-wavenet/wavenet/audio_reader.py", line 127, in __init__
    raise ValueError("Global conditioning is enabled, but file names "
ValueError: Global conditioning is enabled, but file names do not conform to pattern having id.`

I'm sorry, but I just do not understand what I'm doing wrong in the slightest. Any/all assistance is appreciated.

**Comment by HandsomeDevilv112** [comment]
So, I have tried having the corpus in it's own folder, renaming all the files to count up, and tried putting the wavs in the exact same folder as VCTK corpus, and there is just no doin' it. 
I think I'm not doing something correctly with vctk corpus, but I have no idea how, what, or how to fix it. 
I am using music as training data? Would that somehow impact global conditioning? I'm kinda inexperienced, but that seems unlikely

**Comment by mrtnmgs** [comment]
Hi @HandsomeDevilv112 and @ibab, I'm having a similar issue with the file naming convention. It would be great to know how to name the sound files without having to download all of the VCTK corpus files. Thanks for sharing your code @ibab!

**Comment by HandsomeDevilv112** [comment]
My apologies but I've since deleted vctk. I was trying to make music, and global conditioning appears to be for speech only (someone please correct me if I'm wrong)

**Comment by vijay-ravichandran** [comment]
The VCTK Corpus has audio files with names as ```p225_001.wav```. Here, 225 is the speaker ID and the 001 is the utterance ID. The code for audio_reader is written so as to look for this pattern in the name and then extract the corresponding speaker ID. 
So, I recommend you to name you files in such a way.

@HandsomeDevilv112 For now the code has global conditioning on speaker ID only that is read from the filenames as I have mentioned above. If you want to do it any other way, you have to rewrite ```audio_reader.py```. If your music doesn't need any such conditioning, you can just avoid giving that in the arguments during training and generation, and the code will work.

**Comment by HandsomeDevilv112** [comment]
Much obliged! 
I've made a couple sound clips without global conditioning, but wanted to try manipulating it to see if I could get something a little closer to music.
I'm still kinda new to neural networking coding, may I ask you for a starting point to changing audio_reader.py?

**Comment by vijay-ravichandran** [comment]
@HandsomeDevilv112 I hope you have read the WaveNet paper. Global conditioning is when an additional input does not change with time. Here is it used similar to the paper. WaveNet is trained on audio from multiple speakers and the speaker ID is given as the additional input. Thus, one model can later generate speech in the voice of a speaker whose ID is provided.
What do you want to use as the additional input with music?

**Comment by HandsomeDevilv112** [comment]
I'll be honest, at this point I'm just kinda improvising.
And with confirmation that the vctk corpus doesn't do what I thought it did initially, I'll go ahead and close this out as a problem located between the keyboard and chair.
