### ISSUE TITLE
How to continue to train with the saved model?

### ISSUE THREAD

**Issue by toannhu** [ibab/tensorflow-wavenet#299]
I was training the model to step 9200 but suddenly my computer stopped and restarted. How do I continue to train with the saved model.ckpt-9200 in my logdir? Tks

**Comment by andimarafioti** [comment]
You can use: `python train.py --help` to see the help for the training. In there you will find that using the option "--logdir" you can tell the script the directory in which to store the logging information for TensorBoard. If the model already exists, it will restore the state and will continue training. There are other ways to restore a model but for me using the logdir option was the easiest.
