### ISSUE TITLE
Training with raw waveform or mu-law quantized waveform.

### ISSUE THREAD

**Issue by rafaelvalle** [ibab/tensorflow-wavenet#314]
Looking at the code I notice that there are two forms of input data: scalar_input and one-hot.
It's not clear to me if the scalar_input is a raw waveform representation or a the mu-law encoded waveform. Can someone comment on this?

**Comment by TheMarex** [comment]
If you search a little bit in the code you will find that the input is always mu-law encoded [here](https://github.com/ibab/tensorflow-wavenet/blob/master/wavenet/model.py#L633-L634). `scalar_input` only determines if the model uses a one-hot encoding for every data point of the input waveform, or just uses floating point values for each sample.

The downside of that setting is that the generation currently only supports the slow non-incremental mode. If you look at the code you will see there are plenty of `NotImplemented` errors thrown with this setting.
