### ISSUE TITLE
how to understand the time_to_batch and batch_to_time function

### ISSUE THREAD

**Issue by zhf459** [ibab/tensorflow-wavenet#319]
I'm confused by how to create causal layer and the shape transformed many times in time_to-batch and batch_to_time how they work in causal_conv function? thank you

**Comment by rafaelvalle** [comment]
If I'm not mistaken, this code was written at a time when tensorflow didn't have dilated convolutions. 
A way to achieve dilated convolutions with regular convolutions is to slice the data. 

For example consider the following setup:
    single kernel of size 2
    dilation 2 and 
    data d equal to [1, 2, 3, 4, 5, 6]. 

For such a dilated convolution the kernels should be convolved with the following data pairs: 
    [[1,3], [2,4], [3,5], [4,6]. 

In this code, the data d is transformed into d = [[1,3,5], [2,4,6]].
Note that with the data sliced this way, a regular convolution of kernel 2 obtains the same effect as a dilated convolution of kernel size 2 and dilation 2.

HTH

**Comment by zhf459** [comment]
@rafaelvalle  Thank you,I get it.
