### ISSUE TITLE
Singing

### ISSUE THREAD

**Issue by bhack** [ibab/tensorflow-wavenet#32]
It could be really interesting to train with singing solo tracks and [Lilypond](http://lilypond.org/doc/v2.19/Documentation/notation/common-notation-for-vocal-music). But probably could be too hard to collect a datest handing copyrights issues.

**Comment by lemonzi** [comment]
It'll probably be easier to find annotations in MIDI, there are not that
many people transcribing melodies with Lilypond. The issue is usually to
align the annotations to the audio; in speech recognition it's common to
learn the alignment as well as the phoneme discrimination. Datasets from
the MIREX challenges are probably a good starting point for the search.

El dg., 18 set. 2016 a les 6:45, bhack (<notifications@github.com>) va
escriure:

**Comment by bhack** [comment]
There is a Lilypond archive called [Mutopia project](http://www.mutopiaproject.org) but it is for classical music.
Probably for singing could trained using GT from
[Mirex Voice Separation](http://www.music-ir.org/mirex/wiki/2016:Singing_Voice_Separation)

**Comment by sertansenturk** [comment]
Another possible option is to contact audio-lyrics alignment people who are working in a capella singing voice.

I'm not familiar if there are any easy-to-reach datasets but @georgid might help you guys pinpointing some. In fact he has a dataset too (https://github.com/MTG/turkish-makam-acapella-sections-dataset), but I'm not sure if the size is adequate and the music style is too specific for your preferences...

**Comment by basveeling** [comment]
Take a look at MedleyDB, they have F0 annotations for individual stems for a couple hundred songs if I remember correctly:
http://medleydb.weebly.com/

**Comment by woodshop** [comment]
Adding to @lemonzi's suggestion, I recommend checking out @craffel's recently released [Lakh MIDI Dataset](http://www.colinraffel.com/projects/lmd/). It provides a large set of MIDI files that have been aligned to songs in the Million Song Dataset.

**Comment by georgid** [comment]
If you need only f0-annotations, then I can add to the already suggested ones: 
RWC (annotations in MIDI) and iKala datasets. 
Maybe the only dataset big enough for DNNs, which is NOT annotated, but might be worth trying doing it, is: [DAMP](http://ccrma.stanford.edu/damp)
   

If you need lyrics annotations as well have a look at this list:
https://docs.google.com/document/d/1PAIshZ6ZpAl7ad2GiiT6Y3wFyrfFkSj4f0wok6yN4j0/edit?usp=sharing

**Comment by shiba24** [comment]
Hi,
I just tried training on bird's "song", which is commonly used for the study of language in neuroscience, and it seems learning really nice.
I wrote simple background and results on my repo (https://github.com/shiba24/birdsong-generation-project). Although this is not human song or music, any feedback and/or comments will be welcomed if you kindly though it's interesting! Thank you.

**Comment by bhack** [comment]
https://arxiv.org/abs/1704.03809 and http://www.dtic.upf.edu/~mblaauw/IS2017_NPSS/
