### ISSUE TITLE
What should output wave file sound like?

### ISSUE THREAD

**Issue by chanil1218** [ibab/tensorflow-wavenet#33]
From the model of mine trained 1999 steps(It might be so little steps to sound normally), 
It sounds just like [noises](https://github.com/ibab/tensorflow-wavenet/files/478791/generated-1999.wav.zip).

It would be better to give well-trained example output for understanding desired output.

**Comment by lemonzi** [comment]
With a batch size of 1, at 2000 steps the network hasn't even seen each
training example once -- I would run it for a lot longer, like 1 million
steps or so. But you'll need a big machine ;).

It's also not clear whether it's doing what it's supposed to do, that's why
there a few PR working in unit tests for each function now.

**Comment by chanil1218** [comment]
I suspected that my iteration was extremely small(ran on laptop about 2 hours due to automatic termination of training).
So I just want to check my progression with regards to some **checkpoints** that were accomplished by other machines for varying time.

If some of diversely trained model generating outputs and their metadata(steps, batch size and so on) suggested densely(labeled like {batch-size=1, steps=1999}, {batch-size=10, steps=10,000}, {batch-size=1, steps=1,000,000} output), then newbies like me can see the final results of this project and also output changes per iteration.

**Comment by danbri** [comment]
+1 for trained samples (indicating step count)

**Comment by woodshop** [comment]
If I understand the paper correctly, DeepMind is using rather deep networks.

The DM authors mention that the receptive field of their models is approximately 3000 samples. This amounts to the exponential gains provided by ![image](https://cloud.githubusercontent.com/assets/4654379/18637801/a915c7f8-7e5b-11e6-9c22-c20a243857d3.png) hidden layers (without stacking).

The authors mention that stacking "further increases the model capacity and the receptive field size". If stacking is used, you get an additional linear gain in the size of the receptive field but at the price of twice as many layers.

The current default parameters of this project uses two stacks of 9 hidden layers, yielding a receptive field of 1023*. At 16KHz sampling rate, this provides the model with a context of just 64 ms, [shorter than many spoken phonemes](http://www.asel.udel.edu/icslp/cdrom/vol4/301/a301.pdf).

This is all to say that you need some heavy machinery to reproduce DM's results. The fact that @danbri hasn't generated plausible audio is probably just as much related to the size of his network as it is to the limited number of observations provided to the model.

----------------

*My formula for the size of the receptive field is (someone please correct me if I'm wrong): ![image](https://cloud.githubusercontent.com/assets/4654379/18637745/78ad1602-7e5b-11e6-9e84-1c9ff2577dbc.png).

**Comment by ibab** [comment]
@woodshop: Yeah, I've also arrived at the same conclusion. I'm testing 4 stacks of 9 hidden layers at the moment (which should have a receptive field of around 2000 samples).

From the 3000 samples, it sounds like they've used 3 stacks of 10 hidden layers.
This would correspond to a configuration of
```
"dilations": [1, 2, 4, 8, 16, 32, 64, 128, 256, 512,
              1, 2, 4, 8, 16, 32, 64, 128, 256, 512,
              1, 2, 4, 8, 16, 32, 64, 128, 256, 512],
```

**Comment by lemonzi** [comment]
It would be nice to have a friendlier way of specifying dilations, like `[2**i for i in range(9)] * 4`. We could either allow a string in the JSON which will be eval'ed or fix this formula and specify the layers per stack and the number of stacks.

**Comment by ibab** [comment]
Specifying the number of stacks and layers per stack would be a good solution.

**Comment by revolter** [comment]
So, what the output should be? Shouldn't you pass a string that it converts it to speech?

**Comment by pineking** [comment]
@revolter TTS (text to speech) has not been implemented yet. Perhaps it would be released in the future.

**Comment by revolter** [comment]
Ok, so what exactly is this project helping with? (sorry for such a newbie question)

**Comment by ibab** [comment]
The WaveNet network described in the paper was tested on different tasks, only one of which was TTS.
Once we get the simpler problems to work (Audio generation from the VCTK dataset and music generation), we can look for a good dataset for TTS and add that feature.
Note that the DeepMind authors used a proprietary Google dataset to base their TTS demonstration on, so we will have to look for a different one.

**Comment by pineking** [comment]
It is not easy to look for a public, free and high-quality TTS database as the demonstration.
the data from blizzard challenge may be an alternative one:
https://synsig.org/index.php/Blizzard_Challenge
http://www.cstr.ed.ac.uk/projects/blizzard/

**Comment by revolter** [comment]
Well, I have a personal database for training (which I can't share) so I only needed to train it against them and have the TTS function implemented in order to use it.

**Comment by pineking** [comment]
@revolter which language of your database? America English or Mandarin Chinese?
For TTS application, text analysis part is language dependent which converts a text string sequence to a phoneme sequence with linguistic information (see the Appendix A in Wavenet paper). Also, this is difficult to implement compared to speech synthesis part.
As far as I know, https://github.com/CSTR-Edinburgh/merlin only has the speech synthesis part.
while https://github.com/bpotard/idlak has both the text analysis and speech synthesis.

**Comment by revolter** [comment]
Well, I have many languages, didn't know that it's language dependent. But I do have American English and Chinese too (though I don't know if it's Mandarin or not).

**Comment by ibab** [comment]
I think we can answer this issue now:
When using VCTK, the output should sound like the example linked in the `README.md`.
