### ISSUE TITLE
Continuity on trained model

### ISSUE THREAD

**Issue by chanil1218** [ibab/tensorflow-wavenet#35]
It would be great continue learning from the someone's trained model or paused mine.

**Comment by ibab** [comment]
This would be very useful to have. It would involve adding a new argument to the `train.py` script that would get passed the path to the model file. If present, a `tf.Saver` can restore the state from the file.

**Comment by mecab** [comment]
I've just started to working on it, and I think I can raise a PR soon 💃

**Comment by mecab** [comment]
Done, yey! ✌
