### ISSUE TITLE
Can anyone share a pre-trained wavenet model trained on complete VCTK corpus?

### ISSUE THREAD

**Issue by harismuneer** [ibab/tensorflow-wavenet#367]
I don't have the resources right now to train this model on a GPU but i am in urgent need of implementing it for my university project. 

It would be really helpful if any of you could share the trained model files in the logdir here. It would also help others as well. Thanks!

**Comment by raghubetageri** [comment]
if u are with trained model plz can you share me the trained model files. it will be more helpful for me
