### ISSUE TITLE
Separate 1x1 convolution for skip connection

### ISSUE THREAD

**Issue by basveeling** [ibab/tensorflow-wavenet#48]
One of the authors mentioned that the skip connections are connected to a separate 1x1 convolution than the one which output goes into the add block.

**Comment by ibab** [comment]
That's good to know, thanks!
So adjusting the diagram in the paper, it would look like the following, right?

<img width="461" alt="screen shot 2016-09-19 at 17 19 18" src="https://cloud.githubusercontent.com/assets/890531/18637970/88881026-7e8e-11e6-9fcf-bb78b3afed61.png">

**Comment by jyegerlehner** [comment]
I like that better. If someone is going to put this in anytime soon please chime in so we don't duplicate effort.

**Comment by ibab** [comment]
I could add this once #39 is merged.

**Comment by ibab** [comment]
This has been fixed by #70
