### ISSUE TITLE
Bug with trimming

### ISSUE THREAD

**Issue by JesseYang** [ibab/tensorflow-wavenet#59]
I train the network with default hyper-parameters:

`Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jesse/tensorflow_workspace/tensorflow-wavenet/audio_reader.py", line 87, in thread_main
    audio = trim_silence(audio[:, 0])
  File "/home/jesse/tensorflow_workspace/tensorflow-wavenet/audio_reader.py", line 47, in trim_silence
    return audio[indices[0]:indices[-1]]
IndexError: index 0 is out of bounds for axis 0 with size 0`

The error occurs at the last line of trim_silence method:

`return audio[indices[0]:indices[-1]]`

It seems that some audio consists of only silence and is blank after trimming.

**Comment by JesseYang** [comment]
I decreased the threshold for trimming from 0.3 to 0.01, and the training of 4K steps finished without errors. The loss is smaller compared with the 0.3 threshold case, in which the error occurs around 600 steps.

![image](https://cloud.githubusercontent.com/assets/499122/18694625/30e2f380-7fde-11e6-9e71-4dd72b059a4c.png)

**Comment by ibab** [comment]
Okay, we should probably improve the trimming as suggested in #56.
I think that a threshold of 0.01 basically disables the trimming.
In that case, I'm not surprised that the loss is lower, because it's easier to fit the silent parts of the recording (I've seen this effect before when enabling/disabling trimming).

**Comment by mecab** [comment]
I raised PR to suppress the fail at #73 , while I agree that we should improve the trimming algorithm.
