### ISSUE TITLE
Generated samples are non-negative

### ISSUE THREAD

**Issue by hoonyoung** [ibab/tensorflow-wavenet#64]
For my case, all the generated audio samples seem to be positive integer values. 

I used the following architecture for the network. (wavenet_params.json)
    "dilations": [1, 2, 4, 8, 16, 32, 64, 128, 256, 512,
                  1, 2, 4, 8, 16, 32, 64, 128, 256, 512,
                  1, 2, 4, 8, 16, 32, 64, 128, 256, 512],

I wonder if this only happens to me.. and want to know how to fix it.  :)

**Comment by ibab** [comment]
Do you mean the numbers that are printed while it's generating?
Those are the outputs of the neural network, which we transform back into a waveform before saving the audio.

**Comment by hoonyoung** [comment]
no, I used the following command.. and 'generated.wav' file looks like that.

$ python generate.py --wav_out_path=generated.wav --save_every 2000 --samples 16000 model.ckpt-250

Maybe it's somehow related to 'librosa'. The package was not nicely installed in my case, so I had to try a few stuff to make it work. I'll check it again.

**Comment by ibab** [comment]
Okay, this used to be a bug and I thought I had fixed it.
Is it possible that you are running with a version that doesn't include https://github.com/ibab/tensorflow-wavenet/commit/9f85246631d9ffc3d76ae881442c993a5f6e91b6?
I'll look into reproducing this.

**Comment by hoonyoung** [comment]
You're correct. I was using the older version of 'wavenet.py'.  
I'm now retraining the network and will check if it is resolved.  Thank you..  :-)

**Comment by hoonyoung** [comment]
closing this because current version doesn't include this issue anymore.
