### ISSUE TITLE
Bootstrapping the generation with existing audio

### ISSUE THREAD

**Issue by ibab** [ibab/tensorflow-wavenet#68]
Currently, we start the generation with a randomly picked waveform sample.
I wonder what kind of effect that has, considering that the dilated convolutions won't be able to reach backwards beyond the beginning of the generated sample.
Maybe we should start off with one of the audio recordings.

**Comment by mortont** [comment]
I've been testing different hyperparameters using this kind of generation, except I'm starting with the first half of a sample and attempting to generate the second half. So far I haven't had much more luck than the randomly generated waveform, but I've yet to adjust the `dilation_channels` and `residual_channels`. I can post the generated .wav file if there's interest.

**Comment by ibab** [comment]
This will be fixed by #71.

**Comment by lemonzi** [comment]
#71 has been merged, closing.
