### ISSUE TITLE
SyntaxError: non-keyword arg after keyword arg

### ISSUE THREAD

**Issue by Nyrt** [ibab/tensorflow-wavenet#8]
When I try to run train.py, even with the --help flag, I recieve the error:
`  File "train.py", line 40
    parser.add_argument('--num_steps', type=int, default-NUM_STEPS,
SyntaxError: non-keyword arg after keyword arg`
and am thus unable to train the network.
All dependencies (tensorflow, FFmpeg, etc.) are installed.

**Comment by ibab** [comment]
There were some typos in PR #3, but they were fixed by #5, so it should be working again.
