### ISSUE TITLE
Switch to YAML

### ISSUE THREAD

**Issue by lemonzi** [ibab/tensorflow-wavenet#80]
Should we use YAML instead of JSON for the parameters?

👍 : More human-friendly, more compact.
👍 : We can add comments explaining the meaning of each parameter.
👎 : Not native, we would need to add pyYAML to the dependencies.

**Comment by ibab** [comment]
I also like TOML: https://github.com/toml-lang/toml.
YAML can be tricky for user's who are not used to it.

**Comment by lemonzi** [comment]
It's confusing for complex structures, like nested fields, but if we supply an example list of key-value pairs it should be clear enough. It has to be compatible with the flags anyway. I didn't know about TOML, sounds interesting! How's the support? Whichever we pick it should be very easily serializable to a dictionary so that users can generate it with a script for hyperparameter tuning. That, or we wrap training as a library and we use it from the script.

**Comment by ibab** [comment]
This package works analogously to the standard `json` package: https://github.com/uiri/toml
There's also the built-in [`configparser`](https://docs.python.org/3/library/configparser.html) package.

**Comment by ibab** [comment]
While we're properly setting up the configuration management, we might as well try to make the functionality in `train.py` and `generate.py` testable.
I feel like this kind of stuff has probably been solved nicely before, so it should be worth looking out for libraries that manage configuration/command line arguments, etc.

**Comment by lemonzi** [comment]
Since yaml is not an obvious improvement, I'm closing this for the time being until we figure out what to do with the flags.
