### ISSUE TITLE
Can't generate with biases

### ISSUE THREAD

**Issue by jyegerlehner** [ibab/tensorflow-wavenet#87]
There's no way to turn off fast generation that I can find, and a model using biases needs to have it switched off in order to generate. The --fast_generation command line arg is always True no matter what you do.

**Comment by ibab** [comment]
There's a bug in how the arguments are handled. I've fixed this as part of #88.

**Comment by jyegerlehner** [comment]
OK thx ibab. I'll check that #88 fixes it, and if so close the issue.

**Comment by ibab** [comment]
Adding biases to the fast generation is also quite easy. I could do that next.

**Comment by jyegerlehner** [comment]
Is it? The thought crossed my mind when I saw it there and was putting in Xavier init, but I didn't understand all that black magic so didn't want to touch it. Better you than me. :)

**Comment by ibab** [comment]
I've added biases to the fast generation in #88.

**Comment by jyegerlehner** [comment]
@ibab Is #88 meant to be backward compatible with existing checkpoint files? I did a naive merge and tried to generate, and got errors about tensor size mismatch.  First dimension 1 vs. 2. Batch size change? 

I'm guessing to test this I need to restart training from scratch and use that model to generate from in order to test.

**Comment by paperkettle** [comment]
+1 switched branches and seeing variable mismatch, about to retrain and see what that does

**Comment by ibab** [comment]
@jyegerlehner: I've just realized that this was an indication of the bug that I needed to fix :D 
Generating with biases should be working now, so I'm closing the issue.
