### ISSUE TITLE
Fast generation

### ISSUE THREAD

**Issue by maxhodak** [ibab/tensorflow-wavenet#90]
I'm trying to understand the differences between the implementation in `wavenet.py` in this repository and the implementation in @tomlepaine's fast-wavenet. I think I understand the insight in fast-wavenet but are there drawbacks associated with it that mean this repository wouldn't want to just adopt it as the main implementation? Why keep separate "fast" and (presumably) "slow" models?

**Comment by ibab** [comment]
@maxhodak: The slow method is useful to check that the fast method is working. I've used this to add unit tests in #88.

**Comment by tomlepaine** [comment]
I don't think there are any drawbacks of using fast-generation (as long as there are no bugs 😸).

**Comment by DenisSergeevitch** [comment]
Does anyone have a demo of fast generation results? And how much time did it take?

**Comment by ibab** [comment]
@DenisSergeevitch: The fast generation results are identical to the current ones.
I've verified this in #88.
It's still not fast enough for real time applications, but it's enough so that generating several seconds of audio only takes a few minutes.
