### ISSUE TITLE
AudioReader.stop_threads

### ISSUE THREAD

**Issue by jrao1** [ibab/tensorflow-wavenet#91]
There're two issues with this method:

1. The definition is incorrect, it lacks a `self` argument, it should be:`    def stop_threads(self):`    

1. The implementation is problematic, since Python thread object doesn't have a stop() method, there's no official way to stop a thread in Python.

Seems to me we should remove this method all together...

**Comment by ibab** [comment]
Agreed!
We should just remove it.

**Comment by doublecong123** [comment]
Yep! I am recieving this message after training.
"Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/r2d2/projects/tensorflow-wavenet/wavenet/audio_reader.py", line 87, in thread_main
    self.stop_threads()
TypeError: stop_threads() takes no arguments (1 given)"
