### ISSUE TITLE
Generated silence

### ISSUE THREAD

**Issue by yvirin** [ibab/tensorflow-wavenet#97]
Hi,

I followed all the instructions on training a model from the README(from the default dataset). Then I used the generation script to generate a few seconds of sound, again, according to the instructions, but unfortunately I got silence. 

Any idea of what I might got wrong?

**Comment by nakosung** [comment]
Recent commit supports priming. Have you checked this feature?

**Comment by r-zemblys** [comment]
I get an error if I use priming:
```
Traceback (most recent call last):
  File "/home/raimondas/projects/voice/tensorflow-wavenet-ibab/generate.py", line 205, in <module>
    main()
  File "/home/raimondas/projects/voice/tensorflow-wavenet-ibab/generate.py", line 138, in main
    quantization_channels)
  File "/home/raimondas/projects/voice/tensorflow-wavenet-ibab/generate.py", line 92, in create_seed
    return quantized[:cut_index]
  File "/home/raimondas/python-virtualenv/voice/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 313, in _SliceHelper
    if s.stop is not None and s.stop < 0:
  File "/home/raimondas/python-virtualenv/voice/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 529, in __nonzero__
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use the logical TensorFlow ops to test the value of a tensor.
```
Manually setting e.g.  `return quantized[8000:16000]` seems to work.
I'm using Python2 and [dfca1c5](https://github.com/ibab/tensorflow-wavenet/commit/dfca1c597cfb101b582d363b54f971bab9e9e660)

Also what is the reason of :
```
cut_index = tf.size(quantized) + tf.constant(window_size) - tf.constant(1)
return quantized[:cut_index]
```

It does not cut `quantized`, as `cut_index` > `tf.size(quantized) `
Shouldn't it be:
```
cut_index = tf.size(quantized) - tf.constant(window_size) - tf.constant(1)
return quantized[-cut_index:]
```
This is assuming we want to use last samples of seed audio for priming. Although there is a great chance that last samples would be silence and therefore we first need to trim it.

**Comment by ibab** [comment]
@r-zemblys: Yeah, this part of the generation script seems to be broken.

**Comment by mortont** [comment]
You're right, the `cut_index` calculation is wrong at will be fixed pending that PR. But I think it's worth talking about whether or not we should be taking the seed from the beginning or end of the (trimmed) audio. I think it might be more useful to take it from the beginning since you're more likely to cut in the middle of the phoneme that way.

Ultimately, you get a good seed of audio either way, but you could also verify a model by overfitting it on a single sample and then using that same sample as the seed, where the model would predict what follows the seed to a certain time step.

**Comment by jyegerlehner** [comment]
I haven't used priming and I don't get silence.

I got silence early on when there was decode bug where there was integer division. It worked in Python 3 but not 2.7. But that was fixed quite a while ago.

If you run 

```sox yourfile.wav -n stat```

 does it show exactly zero amplitudes? That was characteristic of what I saw when that bug was there.

**Comment by yvirin** [comment]
@jyegerlehner, yes, all zeros. I used the default fast generation. When I used the non fast generation, I got some sound: https://s3-us-west-1.amazonaws.com/amznturk/experimental/generated2.wav

Is that what should be the output like?

**Comment by ibab** [comment]
@yvirin: Which commit are you currently on?

**Comment by yvirin** [comment]
commit dfca1c597cfb101b582d363b54f971bab9e9e660
Author: Igor Babuschkin <igor@babuschk.in>
Date:   Tue Sep 27 23:47:11 2016 +0200

    Restructure code and test generation (#88)

    - Moved the code files into a wavenet package
    - Defined all variables in Wavenet up front so that they can be shared between training and generation methods
    - Renamed WaveNet to WaveNetModel because I want to introduce another class WaveNet that manages all the TensorFlow stuff around WaveNetModel so that the train.py and generate.py scripts should become very simple.
    - Added tests for generation (including a passing test that compares the old and new generation methods)

**Comment by jyegerlehner** [comment]
@yvirin Ah, I've never tried the fast generation yet. That sounds right for early on in the training, using a model with a short receptive field.

**Comment by ibab** [comment]
I haven't tried the fast generation on Python 2 yet, but travis should have caught the problem :/
Maybe there's a Python 2-specific problem in the parts of `generate.py` that are specialized for fast generation.

**Comment by jyegerlehner** [comment]
I pulled the latest master (as of this writing) into the branch I was working in, and used fast generation and it worked (I didn't get zero-amplitude sound. I'm running python 2.7.

**Comment by jyegerlehner** [comment]
I think the generation of all-silence has been repaired.
